# Setup
title:               Euler
tagline:             'A Plaground'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://psireal9.github.io
baseurl:             '/lanyon/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jung Nguyen
  url:               https://twitter.com/psireal99
  email:             nguyed99@zedat.fu-berlin.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
