# Setup
title:               Euler
tagline:             'A Plaground'
description:         'A place to wander and wonder.'
url:                 https://psireal9.github.io
baseurl:             '/lanyon/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jung Nguyen
  url:               https://twitter.com/psireal99
  email:             nguyed99@zedat.fu-berlin.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
